version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts-browsers

    working_directory: ~/repo

    steps:
      - run:
          name: Check versions
          command: |
            node --version
            yarn --version

      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Build
          command: yarn build

      - run:
          name: Unit tests
          # Limit the number of workers to avoid out of memory issues
          # See: https://discuss.circleci.com/t/memory-problems-with-jest-and-workers/10297/3
          command: yarn test:unit --maxWorkers 2

      - run:
          name: Browser-based tests
          # Limit the number of workers to avoid out of memory issues
          # See: https://discuss.circleci.com/t/memory-problems-with-jest-and-workers/10297/3
          command: yarn test:browser

      - run:
          name: Lint
          command: yarn lint

      - run:
          name: Verify build
          command: yarn package

      - run:
          name: Verify Chrome config
          command: yarn build:chrome
