name: 'Create release'
description: 'Creates a 10ten Japanese Reader release'
inputs:
  edge_package_name:
    description: The filename of the Edge package within the dist-edge-package folder
    required: true
  chrome_package_name:
    description: The filename of the Chrome package within the dist-chrome-package folder
    required: true
  firefox_package_name:
    description: The filename of the Firefox package within the dist-firefox-package folder
    required: true
  prerelease:
    description: Whether or not this is a pre-release. Defaults to false.
    default: false
  release_notes:
    description: The draft text to use for the release notes
  version:
    description: The version name for this release
    required: true
outputs:
  url:
    description: 'The release URL'
runs:
  using: 'node16'
  main: 'index.js'
