name: Automated tests
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Build
      run: |
        yarn install
        yarn build
        yarn build:chrome
    - name: Run tests
      env:
        CI: true
      run: |
        yarn test
    - name: Package
      run: yarn package
